server:
  port: 8080

spring:
  application:
    name: spring-boot-tutorial
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/tvseries?stringtype=unspecified
    username: pgdbo
    password: sql
  jackson:
    serialization:
      write-dates-as-timestamps: true  #使用数值timestamp表示日期

mybatis.configuration.mapUnderscoreToCamelCase: true

logging:
  file: target/app.log
  level:
    ROOT: WARN
    cn.devmgr: TRACE
     